urls_list={
    'jp':[
            'http://jp.hao123.com/games',
            'http://vn.hao123.com/games',
            'http://jp.hao123.com/',
            'http://vn.hao123.com/',
            'http://th.hao123.com/',
            'http://th.hao123.com/games',
            'http://th.hao123.com/games/box',
        ],
    'br':{
	    'sync':[
            	'http://br.hao123.com/games',
            	'http://www.fungame.com.br',
            	'http://www.fungame.com.br/box',
	        ],
	    'asyn':[
		'http://www.fungame.com.br/asyn/homest?type=1',
		'http://www.fungame.com.br/asyn/homest?type=0',
		'http://www.fungame.com.br/asyn/rank?type=1',
		'http://www.fungame.com.br/asyn/rank?type=0',
		'http://www.fungame.com.br/asyn/hometag',
		]
	},
    'id':[
            'http://id.hao123.com/',
            'http://id.hao123.com/games',
        ],
    'eg':[
            'http://ar.hao123.com/',
            'http://ar.hao123.com/games',
            'http://sa.hao123.com/',
            'http://sa.hao123.com/games',
        ],
}
